---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
stringData:
  credentials: |
    [default]
    aws access key = value
    aws secret key = value
  config: |
    [default]
    region=eu-west-1