---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: mysql-cluster
type: Opaque
stringData:
  credentials: |
    [default]
    aws access key = value
    aws secret key = value
  config: |
    [default]
    region=eu-west-1

# no need for it if
#    backupSchedules:
#      enabled: false
