# v-1     - this pretty much works 2024-09-24
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  # namespace: mysql-cluster
spec:
  version: "8.4.1"      # Server version: 8.4.1 MySQL Community Server - GPL
  secretName: mysql-secret
  instances: 2
  router:
    version: "8.4.1"    # Server version: 8.4.1-router MySQL Community Server - GPL
    instances: 1
  tlsUseSelfSigned: true
  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "gp3-exp"
    resources:
      requests:
        storage: 4Gi
  backupProfiles:
    - name: s3-bkp
      dumpInstance:
        dumpOptions:
        storage:
          s3:
            bucketName: raf-ojt-bucket 
            prefix: mysql-backup/
            config: s3-secret
            profile: default 
            endpoint: https://s3.eu-west-1.amazonaws.com
  backupSchedules:
    - name: s3-bkp-schedule
      schedule: "*/5 * * * *" 
      backupProfileName: s3-backup 
      enabled: false  
  podSpec:                      # >> OK
    containers:
    - name: mysql
      resources:
        requests:
          memory: "1024Mi"         # "1Gi"="1024Mi"      #"2048Mi"
          cpu: "600m"           # "1800m"
        limits:
          memory: "2048Mi"         # "4Gi"="4096Mi"      #"8192Mi"
          cpu: "1000m"              # "3600m"             # time_zone = UTC this is causing issues to deploy
  mycnf: |
    [mysqld]
    lower_case_table_names=1
    log_bin_trust_function_creators=1
    binlog_expire_logs_seconds=14400  # 4hrs
    innodb_buffer_pool_size=1G
    max_allowed_packet=512M
    


#=========================================================================================
# kubectl rollout restart statefulset <statefulset-name>        to trigger a rolling update. 

# max_allowed_packet=1073741824
# max_allowed_packet=512M   increased from default 64M (67108864)

# kubectl -n mysql-client exec -it rk- -- bash
# cat <<EOF >> .my.cnf
# [client]
# user=root
# password=sakila[]1
# host=mycluster2.mysql-cluster2.svc.cluster.local
# EOF


    # Limits:
    #   cpu:     1
    #   memory:  4Gi
    # Requests:
    #   cpu:      600m
    #   memory:   1Gi

# +-------------------------------+------------+
# | Variable_name                 | Value      |
# +-------------------------------+------------+
# | innodb_buffer_pool_size       | 1073741824 |  1G
# | innodb_buffer_pool_chunk_size | 134217728  |  128MB
#   innodb_buffer_pool_instances     1
# +-------------------------------+------------+

