---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rk-client-pvc         #x1
  namespace: db-tools
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp3-exp
  resources:
    requests:
      storage: 4Gi
