---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: al2023-dp
  namespace: db-tools
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: al2023
  template:
    metadata:
      labels:
        app: al2023
    spec:
      containers:
      - name: al2023
        image: public.ecr.aws/amazonlinux/amazonlinux:2023
        resources:
          requests:
            cpu: "64m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        command: ["sleep","infinity"]
      serviceAccountName: s3-full-access-sa

# kubectl run al2023 --image public.ecr.aws/amazonlinux/amazonlinux:2023 --command sleep infinity
# dnf update -y ; dnf install -y awscli amazon-efs-utils mariadb105 procps tar gzip findutils wget vim

  # # (install mount-s3 command)
  # wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm
  # dnf install mount-s3.rpm
