apiVersion: v1
kind: ConfigMap
metadata:
  name: couchbase-config
data:
  COUCHBASE_USERNAME: "Administrator"
  COUCHBASE_PASSWORD: "password"
  COUCHBASE_BUCKET_NAME: "default"
  COUCHBASE_CLUSTER_SIZE: "3"
