---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-ce
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # terminate app first before deleting argocd application (cleanup)
spec:
  project: default
  source:
    repoURL: https://github.com/rafal321/kubernetes.git
    targetRevision: HEAD
    path: database/couchbase-ce/k8s
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:      # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
      prune: true
      selfHeal: true    # say if manual change then revert
      allowEmpty: true
    syncOptions:
      - Validate=true   # say if invalid field
      - CreateNamespace=false                 # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#prune-last
      - PrunePropagationPolicy=foreground     # https://kubernetes-tutorial.schoolofdevops.com/articles/argo_prune_propogation_policy/
      - PruneLast=true

# PrunePropagationPolicy
# Foreground ; Pods are deleted first, then the ReplicaSet, and finally the Deployment.
# Background ; Deployment is deleted immediately, and the garbage collector takes care of deleting the ReplicaSet and Pods in the background.
# Orphan ; Description: Deletes the parent resource but leaves the child resources untouched.
