---
apiVersion: apps/v1             # x10
kind: Deployment                # x11
metadata:
  name: argo-squares-dep-b      # x12 - to target with HPA we use name not labels
  namespace: argo-squares
  labels:
    app: argo-squares
    color: blue
spec:
  # replicas: 1    # you would never use replicas if horizontal pod autoscaller is in place - it may conflict with argocd etc
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-squares
      color: blue
  template:
    metadata:
      labels:
        app: argo-squares
        color: blue
    spec:
      containers:
      - name: argo-squares
        image: argoproj/rollouts-demo:blue
           # https://hub.docker.com/r/argoproj/rollouts-demo/tags
           # we can test autoscaler as with this settings bad-purple creates a lot of load 
        ports:
        - containerPort: 8080
        resources:
          requests:           # HPA takes requests into account when scaling not the limits
            cpu: "5m"
            memory: "8Mi"    # got OOMKilled with 5Mi
          limits:
            cpu: "10m"
            memory: "10Mi"

# docker pull argoproj/rollouts-demo:slow-purple
# docker pull argoproj/rollouts-demo:bad-purple
# docker pull argoproj/rollouts-demo:purple
# yellow purle green orange blue