---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchbase-config
data:
  COUCHBASE_USERNAME: "Administrator"
  COUCHBASE_CLUSTER_NAME: "aaa-bbb-ccc"
---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-secret
type: Opaque
data:
  COUCHBASE_PASSWORD: cGFzc3dvcmQ=
# stringData:
#   COUCHBASE_PASSWORD: "password"  # here it can be just a string

# echo -n "password" | base64 