apiVersion: v1
kind: Service
metadata:
  name: cbdb-hsvc
  namespace: couchbase-ce
spec:
  clusterIP: None
  selector:
    app: couchbase
  ports:
    - name: couchbase
      port: 8091
      targetPort: 8091

# kubectl port-forward cbdb-sts-0 8091:8091
