apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cbdb-sts
  namespace: couchbase-ce
spec:
  serviceName: cbdb-hsvc
  replicas: 3
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: couchbase:community-7.6.2 # couchbase:community | community-7.6.2
          ports:
            - containerPort: 8091
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          volumeMounts:
            - name: couchbase-pvc
              mountPath: /opt/couchbase/var
          env:
            - name: COUCHBASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: couchbase-config
                  key: COUCHBASE_USERNAME
            - name: COUCHBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase-secret
                  key: COUCHBASE_PASSWORD
            - name: COUCHBASE_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: couchbase-config
                  key: COUCHBASE_CLUSTER_NAME
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 15 && \
                    # Check if this is the first pod (ordinal 0)
                    if [ "${HOSTNAME}" = "cbdb-sts-0" ]; then
                      echo ${COUCHBASE_CLUSTER_NAME} > z0_cluster.txt
                      couchbase-cli cluster-init -c localhost:8091 \
                      --cluster-username ${COUCHBASE_USERNAME} \
                      --cluster-password ${COUCHBASE_PASSWORD} \
                      --cluster-name ${COUCHBASE_CLUSTER_NAME} \
                      --services data,index,query --cluster-ramsize 1024 --cluster-index-ramsize 512
                    else
                      # Join the cluster for other pods
                      echo ${COUCHBASE_CLUSTER_NAME} > z1_cluster.txt
                      couchbase-cli server-add \
                      -c cbdb-sts-0.cbdb-hsvc:8091 \
                      -u ${COUCHBASE_USERNAME} \
                      -p ${COUCHBASE_PASSWORD} \
                      --server-add http://$(hostname -i):8091 \
                      --server-add-username ${COUCHBASE_USERNAME} \
                      --server-add-password ${COUCHBASE_PASSWORD} \
                      --services data,index,query
                    fi
  volumeClaimTemplates:
    - metadata:
        name: couchbase-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3-exp  # gp3-exp | standard
        resources:
          requests:
            storage: 4Gi
