---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-server-secrets
  namespace: mysql-server
data:
  mysqlRootPassword: UEBzc3dvcmQxMjM=   # Example password: P@ssword123
  mysqlUser: dXNlcl8x                   # Example user:     user_1
  mysqlPassword: UEBzc3dvcmQxMjM=       # Example password: P@ssword123

# echo -n XXX | base64
# kubectl -n mysql-server get secret mysql-server-secrets -oyaml | awk '/mysqlRootPassword:/ {print $NF}' | base64 -d ; echo
